### ISSUE TITLE
bug user 

### ISSUE THREAD

**Issue by imamsudarajat04** [syahdham/stisla-laravel-base#1]
bug di user id 2 saat mau ke profile masih ke user id 1

**Comment by syahdham** [comment]
Baik, Mas, terima kasih sebelumnya untuk reportnya.

Apakah alurnya seperti ini mas, maaf supaya saya bisa reproduce bug nya.

John Doe tambah pengguna baru, kemudian pengguna baru tsb login dan klik profile, apakah benar begitu?

**Comment by imamsudarajat04** [comment]
benar kak
